/// 日本百名山(深田久弥)のデータ。
class Mountain {
  const Mountain({
    required this.id,
    required this.name,
    required this.kana,
    required this.elevation,
    required this.prefecture,
  });

  /// 1〜100 の通し番号(北から南の順)。
  final int id;
  final String name;
  final String kana;

  /// 標高(メートル)。
  final int elevation;
  final String prefecture;
}

const List<Mountain> mountains = [
  Mountain(id: 1, name: '利尻岳', kana: 'りしりだけ', elevation: 1721, prefecture: '北海道'),
  Mountain(id: 2, name: '羅臼岳', kana: 'らうすだけ', elevation: 1661, prefecture: '北海道'),
  Mountain(id: 3, name: '斜里岳', kana: 'しゃりだけ', elevation: 1547, prefecture: '北海道'),
  Mountain(id: 4, name: '阿寒岳', kana: 'あかんだけ', elevation: 1499, prefecture: '北海道'),
  Mountain(id: 5, name: '大雪山', kana: 'たいせつざん', elevation: 2291, prefecture: '北海道'),
  Mountain(id: 6, name: 'トムラウシ山', kana: 'とむらうしやま', elevation: 2141, prefecture: '北海道'),
  Mountain(id: 7, name: '十勝岳', kana: 'とかちだけ', elevation: 2077, prefecture: '北海道'),
  Mountain(id: 8, name: '幌尻岳', kana: 'ぽろしりだけ', elevation: 2052, prefecture: '北海道'),
  Mountain(id: 9, name: '羊蹄山', kana: 'ようていざん', elevation: 1898, prefecture: '北海道'),
  Mountain(id: 10, name: '岩木山', kana: 'いわきさん', elevation: 1625, prefecture: '青森県'),
  Mountain(id: 11, name: '八甲田山', kana: 'はっこうださん', elevation: 1585, prefecture: '青森県'),
  Mountain(id: 12, name: '八幡平', kana: 'はちまんたい', elevation: 1613, prefecture: '岩手県・秋田県'),
  Mountain(id: 13, name: '岩手山', kana: 'いわてさん', elevation: 2038, prefecture: '岩手県'),
  Mountain(id: 14, name: '早池峰山', kana: 'はやちねさん', elevation: 1917, prefecture: '岩手県'),
  Mountain(id: 15, name: '鳥海山', kana: 'ちょうかいさん', elevation: 2236, prefecture: '山形県・秋田県'),
  Mountain(id: 16, name: '月山', kana: 'がっさん', elevation: 1984, prefecture: '山形県'),
  Mountain(id: 17, name: '朝日岳', kana: 'あさひだけ', elevation: 1871, prefecture: '山形県・新潟県'),
  Mountain(id: 18, name: '蔵王山', kana: 'ざおうさん', elevation: 1841, prefecture: '山形県・宮城県'),
  Mountain(id: 19, name: '飯豊山', kana: 'いいでさん', elevation: 2128, prefecture: '福島県・山形県・新潟県'),
  Mountain(id: 20, name: '吾妻山', kana: 'あづまさん', elevation: 2035, prefecture: '福島県・山形県'),
  Mountain(id: 21, name: '安達太良山', kana: 'あだたらやま', elevation: 1700, prefecture: '福島県'),
  Mountain(id: 22, name: '磐梯山', kana: 'ばんだいさん', elevation: 1816, prefecture: '福島県'),
  Mountain(id: 23, name: '会津駒ヶ岳', kana: 'あいづこまがたけ', elevation: 2133, prefecture: '福島県'),
  Mountain(id: 24, name: '那須岳', kana: 'なすだけ', elevation: 1917, prefecture: '栃木県'),
  Mountain(id: 25, name: '越後駒ヶ岳', kana: 'えちごこまがたけ', elevation: 2003, prefecture: '新潟県'),
  Mountain(id: 26, name: '平ヶ岳', kana: 'ひらがたけ', elevation: 2141, prefecture: '新潟県・群馬県'),
  Mountain(id: 27, name: '巻機山', kana: 'まきはたやま', elevation: 1967, prefecture: '新潟県'),
  Mountain(id: 28, name: '燧ヶ岳', kana: 'ひうちがたけ', elevation: 2356, prefecture: '福島県'),
  Mountain(id: 29, name: '至仏山', kana: 'しぶつさん', elevation: 2228, prefecture: '群馬県'),
  Mountain(id: 30, name: '谷川岳', kana: 'たにがわだけ', elevation: 1977, prefecture: '群馬県・新潟県'),
  Mountain(id: 31, name: '雨飾山', kana: 'あまかざりやま', elevation: 1963, prefecture: '新潟県・長野県'),
  Mountain(id: 32, name: '苗場山', kana: 'なえばさん', elevation: 2145, prefecture: '新潟県・長野県'),
  Mountain(id: 33, name: '妙高山', kana: 'みょうこうさん', elevation: 2454, prefecture: '新潟県'),
  Mountain(id: 34, name: '火打山', kana: 'ひうちやま', elevation: 2462, prefecture: '新潟県'),
  Mountain(id: 35, name: '高妻山', kana: 'たかつまやま', elevation: 2353, prefecture: '新潟県・長野県'),
  Mountain(id: 36, name: '男体山', kana: 'なんたいさん', elevation: 2486, prefecture: '栃木県'),
  Mountain(id: 37, name: '日光白根山', kana: 'にっこうしらねさん', elevation: 2578, prefecture: '栃木県・群馬県'),
  Mountain(id: 38, name: '皇海山', kana: 'すかいさん', elevation: 2144, prefecture: '栃木県・群馬県'),
  Mountain(id: 39, name: '武尊山', kana: 'ほたかやま', elevation: 2158, prefecture: '群馬県'),
  Mountain(id: 40, name: '赤城山', kana: 'あかぎさん', elevation: 1828, prefecture: '群馬県'),
  Mountain(id: 41, name: '草津白根山', kana: 'くさつしらねさん', elevation: 2160, prefecture: '群馬県'),
  Mountain(id: 42, name: '四阿山', kana: 'あずまやさん', elevation: 2354, prefecture: '群馬県・長野県'),
  Mountain(id: 43, name: '浅間山', kana: 'あさまやま', elevation: 2568, prefecture: '群馬県・長野県'),
  Mountain(id: 44, name: '筑波山', kana: 'つくばさん', elevation: 877, prefecture: '茨城県'),
  Mountain(id: 45, name: '白馬岳', kana: 'しろうまだけ', elevation: 2932, prefecture: '長野県・富山県'),
  Mountain(id: 46, name: '五竜岳', kana: 'ごりゅうだけ', elevation: 2814, prefecture: '長野県・富山県'),
  Mountain(id: 47, name: '鹿島槍ヶ岳', kana: 'かしまやりがたけ', elevation: 2889, prefecture: '長野県・富山県'),
  Mountain(id: 48, name: '剱岳', kana: 'つるぎだけ', elevation: 2999, prefecture: '富山県'),
  Mountain(id: 49, name: '立山', kana: 'たてやま', elevation: 3015, prefecture: '富山県'),
  Mountain(id: 50, name: '薬師岳', kana: 'やくしだけ', elevation: 2926, prefecture: '富山県'),
  Mountain(id: 51, name: '黒部五郎岳', kana: 'くろべごろうだけ', elevation: 2840, prefecture: '富山県・岐阜県'),
  Mountain(id: 52, name: '水晶岳', kana: 'すいしょうだけ', elevation: 2986, prefecture: '富山県'),
  Mountain(id: 53, name: '鷲羽岳', kana: 'わしばだけ', elevation: 2924, prefecture: '長野県・富山県'),
  Mountain(id: 54, name: '槍ヶ岳', kana: 'やりがたけ', elevation: 3180, prefecture: '長野県・岐阜県'),
  Mountain(id: 55, name: '穂高岳', kana: 'ほたかだけ', elevation: 3190, prefecture: '長野県・岐阜県'),
  Mountain(id: 56, name: '常念岳', kana: 'じょうねんだけ', elevation: 2857, prefecture: '長野県'),
  Mountain(id: 57, name: '笠ヶ岳', kana: 'かさがたけ', elevation: 2898, prefecture: '岐阜県'),
  Mountain(id: 58, name: '焼岳', kana: 'やけだけ', elevation: 2455, prefecture: '長野県・岐阜県'),
  Mountain(id: 59, name: '乗鞍岳', kana: 'のりくらだけ', elevation: 3026, prefecture: '長野県・岐阜県'),
  Mountain(id: 60, name: '御嶽山', kana: 'おんたけさん', elevation: 3067, prefecture: '長野県・岐阜県'),
  Mountain(id: 61, name: '美ヶ原', kana: 'うつくしがはら', elevation: 2034, prefecture: '長野県'),
  Mountain(id: 62, name: '霧ヶ峰', kana: 'きりがみね', elevation: 1925, prefecture: '長野県'),
  Mountain(id: 63, name: '蓼科山', kana: 'たてしなやま', elevation: 2531, prefecture: '長野県'),
  Mountain(id: 64, name: '八ヶ岳', kana: 'やつがたけ', elevation: 2899, prefecture: '長野県・山梨県'),
  Mountain(id: 65, name: '両神山', kana: 'りょうかみさん', elevation: 1723, prefecture: '埼玉県'),
  Mountain(id: 66, name: '雲取山', kana: 'くもとりやま', elevation: 2017, prefecture: '東京都・埼玉県・山梨県'),
  Mountain(id: 67, name: '甲武信ヶ岳', kana: 'こぶしがたけ', elevation: 2475, prefecture: '埼玉県・山梨県・長野県'),
  Mountain(id: 68, name: '金峰山', kana: 'きんぷさん', elevation: 2599, prefecture: '山梨県・長野県'),
  Mountain(id: 69, name: '瑞牆山', kana: 'みずがきやま', elevation: 2230, prefecture: '山梨県'),
  Mountain(id: 70, name: '大菩薩嶺', kana: 'だいぼさつれい', elevation: 2057, prefecture: '山梨県'),
  Mountain(id: 71, name: '丹沢山', kana: 'たんざわさん', elevation: 1567, prefecture: '神奈川県'),
  Mountain(id: 72, name: '富士山', kana: 'ふじさん', elevation: 3776, prefecture: '山梨県・静岡県'),
  Mountain(id: 73, name: '天城山', kana: 'あまぎさん', elevation: 1406, prefecture: '静岡県'),
  Mountain(id: 74, name: '木曽駒ヶ岳', kana: 'きそこまがたけ', elevation: 2956, prefecture: '長野県'),
  Mountain(id: 75, name: '空木岳', kana: 'うつぎだけ', elevation: 2864, prefecture: '長野県'),
  Mountain(id: 76, name: '恵那山', kana: 'えなさん', elevation: 2191, prefecture: '長野県・岐阜県'),
  Mountain(id: 77, name: '甲斐駒ヶ岳', kana: 'かいこまがたけ', elevation: 2967, prefecture: '山梨県・長野県'),
  Mountain(id: 78, name: '仙丈ヶ岳', kana: 'せんじょうがたけ', elevation: 3033, prefecture: '山梨県・長野県'),
  Mountain(id: 79, name: '鳳凰山', kana: 'ほうおうざん', elevation: 2841, prefecture: '山梨県'),
  Mountain(id: 80, name: '北岳', kana: 'きただけ', elevation: 3193, prefecture: '山梨県'),
  Mountain(id: 81, name: '間ノ岳', kana: 'あいのだけ', elevation: 3190, prefecture: '山梨県・静岡県'),
  Mountain(id: 82, name: '塩見岳', kana: 'しおみだけ', elevation: 3047, prefecture: '長野県・静岡県'),
  Mountain(id: 83, name: '悪沢岳', kana: 'わるさわだけ', elevation: 3141, prefecture: '静岡県'),
  Mountain(id: 84, name: '赤石岳', kana: 'あかいしだけ', elevation: 3121, prefecture: '長野県・静岡県'),
  Mountain(id: 85, name: '聖岳', kana: 'ひじりだけ', elevation: 3013, prefecture: '長野県・静岡県'),
  Mountain(id: 86, name: '光岳', kana: 'てかりだけ', elevation: 2592, prefecture: '長野県・静岡県'),
  Mountain(id: 87, name: '白山', kana: 'はくさん', elevation: 2702, prefecture: '石川県・岐阜県'),
  Mountain(id: 88, name: '荒島岳', kana: 'あらしまだけ', elevation: 1523, prefecture: '福井県'),
  Mountain(id: 89, name: '伊吹山', kana: 'いぶきやま', elevation: 1377, prefecture: '滋賀県・岐阜県'),
  Mountain(id: 90, name: '大台ヶ原山', kana: 'おおだいがはらやま', elevation: 1695, prefecture: '奈良県・三重県'),
  Mountain(id: 91, name: '大峰山', kana: 'おおみねさん', elevation: 1915, prefecture: '奈良県'),
  Mountain(id: 92, name: '大山', kana: 'だいせん', elevation: 1729, prefecture: '鳥取県'),
  Mountain(id: 93, name: '剣山', kana: 'つるぎさん', elevation: 1955, prefecture: '徳島県'),
  Mountain(id: 94, name: '石鎚山', kana: 'いしづちさん', elevation: 1982, prefecture: '愛媛県'),
  Mountain(id: 95, name: '九重山', kana: 'くじゅうさん', elevation: 1791, prefecture: '大分県'),
  Mountain(id: 96, name: '祖母山', kana: 'そぼさん', elevation: 1756, prefecture: '大分県・宮崎県'),
  Mountain(id: 97, name: '阿蘇山', kana: 'あそさん', elevation: 1592, prefecture: '熊本県'),
  Mountain(id: 98, name: '霧島山', kana: 'きりしまやま', elevation: 1700, prefecture: '宮崎県・鹿児島県'),
  Mountain(id: 99, name: '開聞岳', kana: 'かいもんだけ', elevation: 924, prefecture: '鹿児島県'),
  Mountain(id: 100, name: '宮之浦岳', kana: 'みやのうらだけ', elevation: 1936, prefecture: '鹿児島県'),
];
